import { accountsFixture, transactionFixture } from './finance-fixtures';
import type { Analytics, Budgets, Subscriptions } from '../src/features/insights/types';
export const analyticsFixture: Analytics = {
  asOf: '2026-09-15T12:00:00Z',
  baseCurrency: 'USD',
  accountId: null,
  accounts: accountsFixture.items,
  period: 'month',
  range: {
    dateFrom: '2026-09-01',
    dateTo: '2026-09-15',
    previousFrom: '2026-08-01',
    previousTo: '2026-08-15',
    bucket: 'day',
  },
  fx: { strategy: 'Illustrative current rates', rates: [] },
  spendingMinor: 2240,
  previousSpendingMinor: 2000,
  spendingChangePercent: 12,
  incomeMinor: 5000,
  previousIncomeMinor: 4500,
  incomeChangePercent: 11.1,
  netCashFlowMinor: 2760,
  transfersOutMinor: 0,
  transfersInMinor: 0,
  previousNetCashFlowMinor: 2500,
  transactionCount: 1,
  averageTransactionMinor: 2240,
  trend: [
    { date: '2026-09-01', amountMinor: 0, topCategory: null },
    { date: '2026-09-14', amountMinor: 2240, topCategory: 'dining' },
  ],
  previousTrend: [],
  categories: [
    { category: 'dining', amountMinor: 2240, count: 1, sharePercent: 100, previousMinor: 2000 },
  ],
  merchants: [
    { merchant: transactionFixture.merchant, amountMinor: 2240, count: 1, averageMinor: 2240 },
  ],
  incomeSources: [{ source: 'income', amountMinor: 5000, count: 1 }],
  incomeMerchants: [],
  transactions: {
    items: [{ transaction: transactionFixture, reportingAmountMinor: 2240, feeOnly: false }],
    total: 1,
    page: 1,
    limit: 5,
    totalPages: 1,
  },
};
export const budgetsFixture: Budgets = {
  month: '2026-09',
  baseCurrency: 'USD',
  editable: true,
  items: [
    {
      id: 'budget-dining',
      category: 'dining',
      currency: 'USD',
      amountMinor: 3000,
      spentMinor: 2240,
      enabled: true,
      projectedMinor: 4480,
      projectedOverMinor: 1480,
      remainingMinor: 760,
      usagePercent: 74.7,
      status: 'WITHIN',
      daysRemaining: 16,
      dailyAllowanceMinor: 47,
      revision: 1,
      transactionCount: 1,
      reportAmountMinor: 3000,
      reportSpentMinor: 2240,
    },
  ],
  totalPlannedMinor: 3000,
  totalSpentMinor: 2240,
  daysRemaining: 16,
  fx: 'Current illustrative rates',
};
export const subscriptionsFixture: Subscriptions = {
  asOf: '2026-09-15T12:00:00Z',
  baseCurrency: 'USD',
  accounts: accountsFixture.items,
  items: [
    {
      id: 'sub-netflix',
      label: 'Netflix',
      merchant: { id: 'netflix', name: 'Netflix', icon: 'subscriptions' },
      accountId: 'usd',
      currency: 'USD',
      amountMinor: 1549,
      cadence: 'MONTHLY',
      status: 'ACTIVE',
      source: 'MANUAL',
      revision: 1,
      anchorDate: '2026-09-07',
      nextPaymentDate: '2026-10-07',
      monthlyEquivalentMinor: 1549,
      reportMonthlyMinor: 1549,
      spentThisMonthMinor: 1549,
      spentThisYearMinor: 1549,
      paymentCard: null,
      cardWarning: null,
      lastPaidAt: '2026-09-07T12:00:00Z',
      paymentCount: 1,
      transactions: [],
    },
  ],
  candidates: [
    {
      key: 'eur:spotify',
      merchant: { id: 'spotify', name: 'Spotify', icon: 'subscriptions' },
      accountId: 'eur',
      currency: 'EUR',
      amountMinor: 1099,
      cadence: 'MONTHLY',
      nextPaymentDate: '2026-10-04',
      evidenceIds: ['one', 'two', 'three'],
      lastPaidAt: '2026-09-04T12:00:00Z',
      confidence: 'Three regular payments with similar amounts.',
    },
  ],
  upcoming: [],
  monthlyEquivalentMinor: 1549,
  yearlyEquivalentMinor: 18588,
  upcomingTotalMinor: 1549,
  actualSubscriptionSpendingMinor: 2749,
  month: '2026-09',
};
